# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
  - tox
  - python3 zip_plugin.py

# Deploy uploads the "zip_plugin.py" result to https://artifacts.lizard.net, but
# only when building a tag. It then turns up on https://plugins.lizard.net
deploy:
  provider: script
  skip_cleanup: true
  script: bash upload-artifact.sh
  on:
    tags: true
    repo: nens/threedi-api-qgis-client
    python: 3.7

notifications:
  email: false