version: "3.0"

services:
  qgis:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
      # Note: run 'xhost +localhost' beforehand.
    volumes:
      - .:/tests_directory/
      - profile-dir:/root/.local/share/QGIS/QGIS3/profiles/default
    command: qgis

volumes:
    profile-dir:
